### PR TITLE
Fix Misspelling

### PR DESCRIPTION
**Pull request by jkeam**
Fix misspelling

### CODE REVIEW

**Comment by GustavoCaso** [comment]
Hey @jkeam Thank you so much for the fix. Are you actually using the gem somewhere?

**Comment by jkeam** [comment]
Yep!  Trying it out on my proj now.

**Comment by jkeam** [comment]
Hmm, a bit worried about the test failures.

**Comment by GustavoCaso** [comment]
@jkeam Yes I think they have block the user I was using for testing. Can I ask you how you are using it, because I was thinking of changing it a bit by removing all the `User` interface and make it just simple api wrapper. You are the only one using it so far so I would like to know your useage

**Comment by jkeam** [comment]
I am currently not using the `User` interface.  I actually prefer the simple api wrapper.  So something like this is what I prefer:

```ruby
body = {
    "user_id" => "string",               
    "nickname" => "string",   
    "profile_url" => "string",   
    "issue_access_token" => "boolean"  
}
Sendbird::UserApi.create(body)
```

**Comment by jkeam** [comment]
I prefer simple wrappers for two main reasons:

1.  Less magic - makes the code in the gem easier to grok
2.  More flexible - makes it easier to keep up with the underlying sendbird api

**Comment by GustavoCaso** [comment]
Great @jkeam thanks for the info. I will update the credentials for the test so they are green. And remove all interface logic and push another version. 😄

**Comment by jkeam** [comment]
👍   :)

**Comment by GustavoCaso** [comment]
Thanks @jkeam

**Pull request merged**
